name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: PromojitPaul
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
